<?php

namespace Aldor\GalleryBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoCategoryRepository extends EntityRepository
{

    public function getRecentFromGallery($gallery, $max = 2)    {
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.image', 'i')
            ->leftJoin('p.photos', 'z')
            -> add('orderBy', 'p.date DESC')
            ->where('p.gallery = :gallery')
            ->setParameter('gallery', $gallery)
            ->setMaxResults($max);
        $query = $qb->getQuery();
       $query->useResultCache(true, 360, 'getRecentPhotos'.$gallery.'-'.$max);
        return $query->getResult();

    }

    public function getFromGallery($galleryId)    {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 'i', 'z')
            ->leftJoin('p.image', 'i')
            ->leftJoin('p.photos', 'z')
            -> add('orderBy', 'p.id DESC')
            ->where('p.gallery = :gallery')
            ->setParameter('gallery', $galleryId);
        $query = $qb->getQuery();
        $query->useResultCache(true, 360, 'getPhotosCat'.$galleryId);
        return $query->getResult();

    }

}
