#src/Aldor/InftechBundle/Resources/config/doctrine/Post.orm.yml
Aldor\BlogBundle\Entity\Post:
    type: entity
    repositoryClass: Aldor\BlogBundle\Repository\PostRepository
    table: posts
    indexes:
        id_index:
            columns: [ id ]
        date_index:
            columns: [ date, publicationDateStart  ]

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
            unique: true
        title_slug:
            type: string
            length: 255
    manyToOne:

        category:
            targetEntity: PostCategory
            inversedBy: posts
            joinColumn:
                name: categoryid
                referencedColumnName: id
            fetch: LAZY
            nullable: no
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            # inversedBy: posts
            joinColumn:
                name: userid
                referencedColumnName: id
            fetch: LAZY
            nullable: no
        media:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media

    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: posts
            fetch: EXTRA_LAZY
            joinTable:
                fetch: EXTRA_LAZY
                name: post_tags
                joinColumns:
                     post_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    lifecycleCallbacks:
            prePersist: [ preInsert ]
            preUpdate: [ preUpdate ]
            preRemove: [ preRemove ]
