#src/Aldor/InftechBundle/Resources/config/doctrine/PostCategory.orm.ymL
Aldor\BlogBundle\Entity\PostCategory:
    type: entity
    repositoryClass: Aldor\BlogBundle\Repository\PostCategoryRepository
    table: postcategory
    indexes:
        id_index:
            columns: [ id ]
        slug_index:
            columns: [ slug ]
    id:
        id:
            type: integer
            generator: { strategy :AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        slug:
            type: string
            length: 255
    oneToMany:
        posts:
            targetEntity: Post
            mappedBy: category
            cascade: ["remove", "persist"]
    lifecycleCallbacks:
        prePersist: [ setSlugValue ]
        preUpdate: [ setSlugValue ]

