imports:
    - { resource: config.yml }

assetic:
    use_controller: true

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
web_profiler:
    toolbar: true
    intercept_redirects: false
# jms_debugging:
#     # You can set this to true if you want to automatically retrieve help
#     #     # messages for public exceptions. If you leave this set to false, you have
#     #         # to click the "search" button manually each time.
#         auto_help: true
monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info


#swiftmailer:
#    delivery_address: me@example.com
