ekino_new_relic:
    enabled: true                         # Defaults to true
    application_name:  mkaciuba.pl
                                          # as php ini-value
    api_key:                              # New Relic API
    license_key:                          # New Relic license key (optional, default value is read from php.ini)
    xmit: false                           # if you want to record the metric data up to the point newrelic_set_appname is called, set this to true
    logging: false                        # If true, logs all New Relic interactions to the Symfony log
    instrument: true                     # If true, uses enhanced New Relic RUM instrumentation (see below)
    log_exceptions: true                 # If true, sends exceptions to New Relic
    log_commands: false                    # If true, logs CLI commands to New Relic as Background jobs (>2.3 only)
    using_symfony_cache: true            # Symfony HTTP cache (see below)
    transaction_naming: route             # route, controller or service (see below)
    transaction_naming_service: ~         # Transaction naming service (see below)
    ignored_routes: []                    # No transaction recorded for this routes
    ignored_paths: []                     # No transaction recorded for this paths
    ignored_commands: []                  # No transaction recorded for this commands (background tasks)
