aldor_api:
    resource: "@AldorApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1/

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

mkaciuba_old_karnawal:
    path: /karnawal2013{url}
    requirements:
        url: .*
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: gallery_photocategory
        permanent: true
        galleryslug: "stowarzyszenie"
        photocategoryslug: "karnawal-2013"

mkaciuba_old_15lecie:
    path: /15lecie{url}
    requirements:
        url: .*
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: gallery_photocategory
        permanent: true
        galleryslug: "stowarzyszenie"
        photocategoryslug: "15lecie"

fos_user_registration_register:
    path: /login
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true

sonata_page_exceptions:
    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'
    prefix: /

sonata_page_cache:
    resource: '@SonataPageBundle/Resources/config/routing/cache.xml'
    prefix: /

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

aldor_blog:
    resource: "@AldorBlogBundle/Resources/config/routing.yml"
    prefix:   /blog
aldor_gallery:
    resource: "@AldorGalleryBundle/Resources/config/routing.yml"
    prefix:   /galeria
aldor_portfolio:
    resource: "@AldorPortfolioBundle/Resources/config/routing.yml"
    prefix:   /projekty
inftech_search:
    pattern: /szukaj/{search}/{page}
    defaults: { _controller: AldorInftechBundle:Search:index, search: null, page: 1 }

_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_media_pixlr:
    resource: '@SonataMediaBundle/Resources/config/routing/pixlr.xml'
    prefix: /admin/media


sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /


nelmio_security:
    path:     /nelmio/csp/report
    defaults: { _controller: nelmio_security.csp_reporter_controller:indexAction }
    methods:  [POST]


remove_trailing_slash:
    path: /{url}
    defaults: { _controller: AldorInftechBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]


remove_trailing_slash_begin:
    path: /{url}
    defaults: { _controller: AldorInftechBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: \/{2,}?.*
    methods: [GET]
