
sonata_admin:
    title:     Admin Panel
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
       # default global templates
        layout:  SonataAdminBundle::layout.html.twig
        # layout:  AldorBackendBundle:Dashboard:layout.html.twig

        ajax:   SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:   SonataAdminBundle:CRUD:list.html.twig
        show:   SonataAdminBundle:CRUD:show.html.twig
        edit:   SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
    options:
        html5_validate:                         true      # use html5 validation
        confirm_exit:                           true      # enabled confirmation when quitting with unsaved changes
        use_select2:                            true      # enable select2
        use_icheck:                             false     # enable iCheck
    security:
        handler: sonata.admin.security.handler.acl
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
        # acl security information
        #
    assets:
        stylesheets:
            - bundles/sonataadmin/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/ionicons.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/AdminLTE.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonataadmin/vendor/select2/select2.css
            - bundles/sonataadmin/vendor/select2/select2-bootstrap.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonatapage/sonata-page.back.min.css
        javascripts:

            # Defaults:
            - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonataadmin/vendor/select2/select2.min.js
            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js
            - bundles/sonatapage/sonata-page.back.js

