<?php

namespace Aldor\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCategoryRepository extends EntityRepository
{
    function getCategory($galleryslug,$categoryslyg)
    {


    }


}
