#src/Aldor/InftechBundle/Resources/config/doctrine/Tag.orm.yml
Application\Sonata\MediaB\Entity\Media:
    type: entity
    indexes:
        id_index:
            columns: [ id ]
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    oneToMany:
        posts:
            targetEntity: Aldor\BlogBundle\Entity\Post
            inversedBy: media
            fetch: LAZY
